config/routes.rb
Rails.application.routes.draw do
  get 'report_user/new'

  get 'report_user/create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post '/report/create' => 'report#create'
  post '/report_user/create' => 'report_user#create'

  get '/report/new' => 'report#new'

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users

  get '/profile' => 'profile#current_show'
  get '/profile/contents' => 'profile#contents'
  get '/profile/suggested_users' => 'profile#suggested_users'

  get '/profile/show/:id' => 'profile#show'
  get '/profile/edit/:id' => 'profile#edit'
  post '/profile/update' => 'profile#update'

  resources :contents do
    collection do
      get :search
      get :recommendations
    end
  end

  get '/:content_type/search' => 'contents#search'

  get '/comment/new/:content_id' => 'comment#new'
  post '/comment/create' => 'comment#create'
  get '/comment/list' => 'comment#list'
  get '/favorite/create' => 'favorite#create'
  get '/pending/create' => 'pending#create'
  get '/review/new/:content_id' => 'review#new'
  post '/review/create' => 'review#create'

  root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :content
	belongs_to :user
	
end

app/models/content.rb
class Content < ActiveRecord::Base
	has_many :comments
	has_many :reviews

  ratyrate_rateable "score"

  TYPES = [ 'movie', 'tv_show', 'videogame' ]

  def self.search(term, content_type = :movie)
    content_type = content_type.to_s.to_sym

    case content_type
      when :movie
        Tmdb::Movie.find(term).map { |movie|
          if movie.poster_path.present?
            Content.where(remote_id: movie.id, content_type: 'movie').first_or_create do |content|
              content.name = movie.original_title
              content.year = movie.release_date.to_s.split('-').first
              content.description = movie.overview
              content.poster = [TMDB_CONFIGURATION[:base_url], TMDB_CONFIGURATION[:poster_sizes].last, movie.poster_path].join
              content.content_type = 'movie'
              content.remote_id = movie.id

              trailers = Tmdb::Search.new("/#{Tmdb::Movie.endpoints[:singular]}/#{Tmdb::Movie.endpoint_id + movie.id.to_s}/videos").fetch_response

              if trailers && trailers['results']
                trailer = trailers['results'].first

                if trailer && trailer['site'] == 'YouTube'
                  content.trailer_id = trailer['key']
                end
              end
            end
          end
        }.compact
      when :tv_show
        Tmdb::TV.find(term).map { |tv_show|
          if tv_show.poster_path.present?
            Content.where(remote_id: tv_show.id, content_type: 'tv_show').first_or_create do |content|
              content.name = tv_show.original_name
              content.year = tv_show.first_air_date.to_s.split('-').first
              content.description = tv_show.overview
              content.poster = [TMDB_CONFIGURATION[:base_url], TMDB_CONFIGURATION[:poster_sizes].last, tv_show.poster_path].join
              content.country = tv_show.origin_country.first
              content.content_type = 'tv_show'
              content.remote_id = tv_show.id

              trailers = Tmdb::Search.new("/#{Tmdb::TV.endpoints[:singular]}/#{Tmdb::TV.endpoint_id + tv_show.id.to_s}/videos").fetch_response

              if trailers && trailers['results']
                trailer = trailers['results'].first

                if trailer && trailer['site'] == 'YouTube'
                  content.trailer_id = trailer['key']
                end
              end
            end
          end
        }.compact
      when :videogame
        search = GiantBomb::Search.new
        search.limit(16)
        search.resources('game')
        search.query(term)
        search.fetch.map { |videogame|
          videogame = GiantBomb::Game.new(videogame)

          if videogame.image && (videogame.image['super_url'] || videogame.image['medium_url'])
            Content.where(remote_id: videogame.id, content_type: 'videogame').first_or_create do |content|
              content.name = videogame.name
              content.year = videogame.original_release_date.to_s.split('-').first
              content.description = videogame.description
              content.poster = videogame.image['super_url'] || videogame.image['medium_url']
              content.content_type = 'videogame'
              content.remote_id = videogame.id

              if videogame.videos && videogame.videos.any? && videogame.videos.first.youtube_id
                content.trailer_id = videogame.videos.first.youtube_id
              end
            end
          end
        }.compact
    end
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	
	belongs_to :user
	
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/pending.rb
class Pending < ActiveRecord::Base
  belongs_to :user
  belongs_to :content
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/report.rb
class Report < ActiveRecord::Base
   
	belongs_to :user
end

app/models/report_user.rb
class ReportUser < ActiveRecord::Base
    	belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
	
	belongs_to :content
	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :favorites
  has_many :reviews


  ratyrate_rater
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @contents = Content.last(12)
  end

  def show
    @content = Content.find(params[:id])
  rescue
    redirect_to contents_path
  end

  def search
    @term = params[:term]
    @content_type = params[:content_type].present? ? params[:content_type].singularize.to_sym : :movie

    if @term.present?
      @results = Content.search(@term, @content_type)
    else
      @results = []
    end
  end

  def recommendations
    data = User.all.inject({}) do |hash, user|
      hash[user.email] = Rate.where(rater_id: user.id).inject({}) do |rate_hash, rate|
        rate_hash[rate.rateable_id] = rate.stars
        rate_hash
      end

      hash
    end

    suggestor = Suggestor::Suggestor.new(data)
    @recommended_contents = suggestor.recommended_to(current_user.email)
    recommended_contents_ids = @recommended_contents.map { |item| item.first }

    @recommendations = Content.where(id: recommended_contents_ids)
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h6 class="header light red-text">#{sentence}</h6>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/pending_helper.rb
module PendingHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/contents/_grid.html.erb
<% contents.in_groups_of(4, false) do |group| %>
  <div class="row">
    <% group.each do |content| %>
      <div class="col s3">
        <div class="card">
          <div class="card-image">
            <img src="<%= content.poster %>">
            <span class="card-title"><%= content.name %></span>
          </div>
          <div class="card-action">
            <% if content.persisted? %>
              <a href="<%= content_path(content) %>">+ Info</a>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/contents/index.html.erb
<h4 class="header light red-text text-lighten-2">Últimos agregados</h4>
<%= render "grid", contents: @contents %>

app/views/contents/recommendations.html.erb
<h4 class="header light red-text text-lighten-2">Recomendaciones</h4>
<!--<%= debug @recommendations %> -->
<!-- <%= debug @recommended_contents %> -->
<%= render "grid", contents: @recommendations %>

app/views/contents/search.html.erb
<h4 class="header light red-text text-lighten-2">Buscar</h4>

<div class="row">
  <form class="input-field col s12">
    <input placeholder="Ingrese un nombre" name="term" type="text" value="<%= @term %>">
    <input type="hidden" name="content_type" value="<%= @content_type %>">
  </form>
</div>

<% if @results.present? %>
  <%= render "grid", contents: @results %>
<% end %>

app/views/contents/show.html.erb
<h4 class="header light red-text text-lighten-2"><%= @content.name %> <%= @content.year? ? "(#{@content.year})" : '' %></h4>
<div class="row">
  <div class="col s3">
    <div class="card">
      <div class="card-image">
        <img src="<%= @content.poster %>">
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <a href="/pending/create?content_id=1" class="waves-effect waves-light btn white-text"><i class="material-icons left">query_builder</i>Pendiente</a>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <a href="/favorite/create?content_id=1" class="waves-effect waves-light btn white-text"><i class="material-icons left">grade</i>Favorito</a>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <%= rating_for @content, "score", disable_after_rate: true, star_off: asset_path('star-off.png'), star_on: asset_path('star-on.png'), star_half: asset_path('star-half.png'), cancel_on: asset_path('cancel-on.png'), cancel_off: asset_path('cancel-off.png'), star_path: '' %>
      </div>
    </div>
  </div>
  <div class="col s9">
    <div class="row">
      <%= raw @content.description.html_safe %>
    </div>

    <% if @content.trailer_id.present? %>
      <div class="video-container no-controls">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @content.trailer_id %>" frameborder="0" allowfullscreen></iframe>
      </div>
    <% end %>

    <div class="row">
      <%= render_shareable %>
    </div>

    <h5 class="header center light-blue-text">
    	Nuevo Comentario
    </h5>

    <%= form_tag("/comment/create", method: "post") do %>
    	<h5 class="header col s12 light">
    		<%= hidden_field_tag(:content_id, @content_id) %>
    		<p>Comentario</p>
    		<%= text_area_tag(:body) %>
    		<%= submit_tag("Crear comentario") %>
    	</h5>
    <% end %>
  </div>
</div>